const fs = require('fs');
const path = require('path');

const ROOT_DIR = __dirname;
const README_PATH = path.join(ROOT_DIR, 'README.md');

// Files to ignore from the index table
const IGNORED_FILES = new Set([
  'update_readme.js',
  '.gitignore',
  'README.md',
  'package.json',
  'package-lock.json',
  'SESSION.md',
  'AGENTS.md',
  'CONTRIBUTING.md'
]);

// Map of known topics or auto-formatter
function getTopicDetails(filename) {
  const mapping = {
    'parallel_limit.js': {
      title: 'Parallel Execution Limit',
      category: 'Async / Concurrency',
      concept: 'Worker Pool pattern, `Promise.all`'
    },
    'currying.js': {
      title: 'Fixed Currying',
      category: 'Functional JS',
      concept: 'Closure memory, recursion, rest operator'
    },
    'infiniteCurry.js': {
      title: 'Infinite Currying',
      category: 'Functional JS',
      concept: '`()` empty call terminator, closures'
    },
    'debounce_throttle.js': {
      title: 'Debounce & Throttle',
      category: 'Performance & Timing',
      concept: '`clearTimeout`, `isWaiting` cooldown flag'
    },
    'deep_comparison.js': {
      title: 'Deep Comparison / Deep Equal',
      category: 'Objects & Recursion',
      concept: 'Structural equality, `Object.hasOwn`, `Object.is`, recursive keys'
    },
    'deepClone.js': {
      title: 'Deep Clone with Circular Reference',
      category: 'Objects & Recursion',
      concept: 'Recursion, `WeakMap` for circular references'
    },
    'once.js': {
      title: 'Once Function Execution',
      category: 'Functional JS / Closures',
      concept: 'Closure flag (`hasRun`), result caching'
    },
    'counter_using_closures.js': {
      title: 'Counter using Closures',
      category: 'Closures & Scope',
      concept: 'Lexical scoping, encapsulation, state preservation'
    },
    'angular hooks': {
      title: 'Angular Lifecycle Hooks',
      category: 'Angular Core',
      concept: 'Component lifecycle, Change Detection'
    },
    'autocomplete_search.html': {
      title: 'Autocomplete Search Box (Typeahead)',
      category: 'DOM & Machine Coding',
      concept: 'Fetch suggestions, event delegation, outside click dismissal'
    },
    'lru_cache.js': {
      title: 'LRU Cache (Least Recently Used)',
      category: 'Data Structures',
      concept: '`Map` insertion-order / Doubly Linked List, $O(1)$ get & put'
    },
    'promise_all.js': {
      title: 'Promise.all & Polyfills',
      category: 'Async / Promises',
      concept: 'Custom `Promise.all`, `allSettled`, `race` implementation'
    },
    'deep_clone.js': {
      title: 'Deep Clone with Circular Reference',
      category: 'Objects & Recursion',
      concept: 'Recursion, `WeakMap` for circular references'
    },
    'event_emitter.js': {
      title: 'Event Emitter (PubSub)',
      category: 'Design Patterns',
      concept: '`on`, `off`, `emit`, `once` subscription system'
    },
    'memoize.js': {
      title: 'Function Memoization',
      category: 'Functional JS',
      concept: 'Higher-order function, argument serialization cache'
    },
    'pipe_compose.js': {
      title: 'Pipe & Compose Functions',
      category: 'Functional JS',
      concept: 'Unary function chaining with `reduce` & `reduceRight`'
    },
    'flatten_array.js': {
      title: 'Flatten Nested Array & Object',
      category: 'Recursion & Arrays',
      concept: 'Recursive flattening, custom depth control'
    },
    'custom_bind.js': {
      title: 'Function.prototype.bind Polyfill',
      category: 'Core JS & Prototypes',
      concept: 'Context binding (`this`), partial application'
    },
    'retry_promise.js': {
      title: 'Async Retry with Exponential Backoff',
      category: 'Async / Resilience',
      concept: 'Automatic API retries, delay multiplication'
    },
    'task_runner.js': {
      title: 'Sequential & Batch Task Runner',
      category: 'Async / Concurrency',
      concept: 'Sequential execution with `reduce`, async queue'
    }

  };

  if (mapping[filename]) {
    return mapping[filename];
  }

  // Fallback auto-formatter for any new file added in future
  const cleanName = filename.replace(/\.js$/, '').replace(/[_-]/g, ' ');
  const capitalized = cleanName.charAt(0).toUpperCase() + cleanName.slice(1);
  return {
    title: capitalized,
    category: filename.endsWith('.js') ? 'JavaScript' : 'Concept',
    concept: 'Interview Solution'
  };
}

function updateReadme() {
  if (!fs.existsSync(README_PATH)) {
    console.error('README.md not found!');
    return;
  }

  const files = fs.readdirSync(ROOT_DIR).filter(file => {
    if (IGNORED_FILES.has(file)) return false;
    if (file.startsWith('.')) return false;
    const stat = fs.statSync(path.join(ROOT_DIR, file));
    return stat.isFile();
  });

  // Sort files nicely
  files.sort();

  let table = '\n<!-- This section is automatically generated by running: node update_readme.js -->\n\n';
  table += '| # | Topic / Problem | File Link | Category | Key Concept |\n';
  table += '|---|---|---|---|---|\n';

  files.forEach((file, index) => {
    const details = getTopicDetails(file);
    const encodedLink = `./${encodeURIComponent(file)}`;
    table += `| ${index + 1} | **${details.title}** | [\`${file}\`](${encodedLink}) | ${details.category} | ${details.concept} |\n`;
  });

  table += '\n';

  const readmeContent = fs.readFileSync(README_PATH, 'utf8');
  const startMarker = '<!-- AUTO-GENERATED-INDEX:START -->';
  const endMarker = '<!-- AUTO-GENERATED-INDEX:END -->';

  const startIndex = readmeContent.indexOf(startMarker);
  const endIndex = readmeContent.indexOf(endMarker);

  if (startIndex === -1 || endIndex === -1) {
    console.error('Markers <!-- AUTO-GENERATED-INDEX:START --> and <!-- AUTO-GENERATED-INDEX:END --> not found in README.md');
    return;
  }

  const newReadme = 
    readmeContent.substring(0, startIndex + startMarker.length) +
    table +
    readmeContent.substring(endIndex);

  fs.writeFileSync(README_PATH, newReadme, 'utf8');
  console.log(`✅ README.md successfully updated with ${files.length} tracked files!`);
}

updateReadme();
